---
name: 'Release management'
permissions:
  contents: write
on:
  push:
    branches: ['main']
    tags: ['*']
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16
        with:
          extra-conf: |
            accept-flake-config = true
          diagnostic-endpoint: ''

      - name: Set Git User Info and pull eventual changes
        run: |
          git switch main
          git pull --rebase
          git config user.name 'Temeraire'
          git config user.email 'actions@chaotic.cx'

      - name: Generate changelog
        run: nix develop -c cz changelog --incremental

      - name: Commit Changelog
        run: |
          git add CHANGELOG.md
          git commit -m "docs(CHANGELOG.md): update" || echo "No changes to commit"
          git push origin HEAD:main

      - name: Get only latest release notes
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          nix develop -c cz changelog --dry-run > CHANGELOG.temp

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.temp
          fail_on_unmatched_files: true
          token: ${{ secrets.GITHUB_TOKEN }}
