---
name: 'Release management'
on:
  push:
    tags: ['*']
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Git User Info and pull eventual changes
        run: |
          git switch main
          git pull --rebase
          git config user.name 'Temeraire'
          git config user.email 'actions@chaotic.cx'

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose -o CHANGELOG.md
          github_token: ${{ github.token }}
        env:
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit changelog
        run: |
          git checkout main
          git config user.name 'Temeraire'
          git config user.email 'actions@chaotic.cx'
          git add CHANGELOG.md
          git commit -m "docs(CHANGELOG.md): update"
          git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" main

      - name: Generate a changelog for the latest release
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose --latest --strip header -o CHANGES.md
        env:
          GITHUB_REPO: ${{ github.repository }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGES.md
          fail_on_unmatched_files: true
          token: ${{ secrets.GITHUB_TOKEN }}
